### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by arve0** [NorwegianKiwi/codeclub-viewer#6]
Steps to produce:

```
git clone https://github.com/NorwegianKiwi/codeclub-viewer.git
git clone https://github.com/kodeklubben/oppgaver.git
cd codeclub-viewer
npm install
npm run build
npm run serve
```

Gives these errors:
```
ERROR in ./~/json-loader!./~/front-matter-loader?onlyAttributes!../oppgaver/src/appinventor/MapIt/MapIt.md
Module build failed: YAMLException: incomplete explicit mapping pair; a key node is missed at line 1, column 14:
    title: Map It: Displaying Locations on a Goog ... 
                 ^
    at generateError (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:994:9)
    at composeNode (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at Object.load (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at parse (/home/arve/codeclub-viewer/node_modules/front-matter/index.js:40:27)
    at extractor (/home/arve/codeclub-viewer/node_modules/front-matter/index.js:23:12)
    at Object.module.exports (/home/arve/codeclub-viewer/node_modules/front-matter-loader/index.js:10:20)
 @ ./~/combine-loader/lib?{"frontmatter":["json","front-matter?onlyAttributes"]}!../oppgaver/src/appinventor/MapIt/MapIt.md 1:33-129

ERROR in ./~/html-loader!./~/markdown-it-loader!./~/front-matter-loader?onlyBody!../oppgaver/src/appinventor/MapIt/MapIt.md
Module build failed: YAMLException: incomplete explicit mapping pair; a key node is missed at line 1, column 14:
    title: Map It: Displaying Locations on a Goog ... 
                 ^
    at generateError (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:994:9)
    at composeNode (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at Object.load (/home/arve/codeclub-viewer/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at parse (/home/arve/codeclub-viewer/node_modules/front-matter/index.js:40:27)
    at extractor (/home/arve/codeclub-viewer/node_modules/front-matter/index.js:23:12)
    at Object.module.exports (/home/arve/codeclub-viewer/node_modules/front-matter-loader/index.js:10:20)
 @ ./~/combine-loader/lib?{"frontmatter":["json","front-matter?onlyAttributes"],"content":["html","markdown-it","front-matter?onlyBody"]}!../oppgaver/src/appinventor/MapIt/MapIt.md 1:141-243

ERROR in ./~/html-loader!./~/markdown-it-loader!./~/front-matter-loader?onlyBody!../oppgaver/src/javafx/fxmllogo/fxmllogo.md
Module not found: Error: Cannot resolve 'file' or 'directory' ../../assets/img/ccno_logo.png in /home/arve/oppgaver/src/javafx/fxmllogo
 @ ./~/html-loader!./~/markdown-it-loader!./~/front-matter-loader?onlyBody!../oppgaver/src/javafx/fxmllogo/fxmllogo.md 1:724-765
```

Page renders at first, but gives error in console:

```
webpackMissingModule — MapIt.md:1Error: Cannot find module "-!json!front-matter?onlyAttributes!/home/arve/oppgaver/src/appinventor/MapIt/MapIt.md"
```

Click on icons, url updates, but nothing happens. Refreshing when `/appinventor`, get blank page. 😢 

Live here: http://spole.seljebu.no:8080/

**Comment by arve0** [comment]
Seems to only be related to appinventor.

**Comment by kristandre** [comment]
Fixed?

**Comment by NorwegianKiwi** [comment]
@arve0: Does this work for you now?

**Comment by arve0** [comment]
I'm at vacation, back in July.

**Comment by arve0** [comment]
I'm at vacation, back in July.
